---
functional:
  - У пользователя должна быть возможность авторизации
  - Решение задачи на скорость против другого игрока.
  - Во время игры оба игрока видят друг у друга редактор с кодом
  - Во время игры оба игрока видят друг у друга вывод тестов
  - Оба игрока могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом (игра будет
    доступна по ссылке)
  - Можно выбрать игру по уровню сложности.
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана
    наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи.
  - Пользователи получают очки, на основе которых строится рейтинг за неделю,
    месяц и за все время
  - Для того чтобы начать игру, нужно нажать на кнопку Создать игру
  - Каждый игрок видит код своего соперника в режиме он-лайн.
  - У каждого игрока есть опция "проверить" для проверки своего решения. Попыток
    проверки использования.
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть.
    Первый в любой момент игра, пока она не закончена, может переподключиться в
    игре.
  - Когда один из игроков находит верное решение, обоим игрокам открывается
    модное окно, где написано, кто является победителем этой игры.
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у
    него появилась. Кнопка "проверить" у него более неактивна, но он может
    остаться и посмотреть ещё раз на свой код.
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у
    него появилась. Кнопка "проверить" у него более неактивна, но он может
    остаться и посмотреть ещё раз на свой код.
  - Соперник тоже может выйти, а может доиграть до конца.
  - Страница игры делится на два редактора. Слева - своего редактора, справа – соперника
  - Наверху находится время игры и ниже - задание (позже будет ещё чат слева)
  - Справа от окошка с заданием находится чат
  - Редактор для ввода кода выглядит как проигрыватель
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
implicit:
  - Мультиязычность. Добавить возможность перевода на русский язык сам сайт
  - Добавить возможность обновить Пароль, Логин, Почту.
  - Добавить возможность удаление аккаунта.
